@Corridor.Legacy_HostAddress = http://localhost:8000

### Anonymous health endpoint.

GET {{Corridor.Legacy_HostAddress}}/healthz
Accept: application/json

### Service WSDL (SoapUI and the portal client import this).

GET {{Corridor.Legacy_HostAddress}}/TraceLink.svc?wsdl
Accept: text/xml

###
